### ISSUE TITLE
Nozzle 2 Issue

### ISSUE THREAD

**Issue by c-riegel** [mattthebaker/Smoothieware-CHMT#3]
Hi Matt,

Maybe this is an OpenPnP issue, but when I move my 48VB, nozzle 2 always does a little jump like in the video I've attached.  It doesn't do this when instructed to jog in just x or y, but every other move (move to camera location, park, move to feeder location) causes this little dance.

Does your machine do this?

Thanks,
Chris

[n2.zip](https://github.com/mattthebaker/Smoothieware-CHMT/files/3342185/n2.zip)

**Comment by mattthebaker** [comment]
Hi Chris,

I haven't seen my machine do that. If the nozzle is in the home position, it shouldn't be able to move up at all.  Possibly something put the nozzle in a slightly lowered state at some point, and the openpnp safe-z move logic is retracting it before moving.

Does it still do that after power cycling the machine and/or hitting home in openpnp? Also, are the two nozzle holders level at the bottom, or is n2 lower?

Matt

**Comment by c-riegel** [comment]
I'm still very new to OpenPnP...  
This was due to the Z nozzle offset being 8.5 for N1 and 7.5 for N2.

Now I have to figure out how to config these ReferenceDragFeeders
